config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :resources
  resources :discovers
  resources :orders
  resources :settings
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :member
  end
  resource :setting
  resources :skus do
    get 'base', on: :collection
  end
  resources :visitors
  resources :businesses
  resources :adverts
  resources :discovers
  resources :goods do
    get 'recommends', on: :collection
  end

  namespace :api, defaults: { format: :json } do
    post :adverts, to: 'base#adverts'
    post :discovers, to: 'base#discovers'
    post :recommends, to: 'base#recommends'
    post :detail, to: 'base#detail'
    get 'adverts' => 'goods#adverts'
    get 'discovers' => 'goods#discovers'
    # get 'login' => 'base#login'
    scope :sms do
      get 'send' => 'base#send_verify'
    end
    scope :wechat do
      get 'jscode2session', to: 'wechat#jscode2session'
    end

    scope :users do
      get 'register', to: 'users#register'  # 绑定手机
      get 'info', to: 'users#info'  # 用户信息(手机绑定)
      get 'browses', to: 'users#browses'  # 所有浏览记录(足迹)
      get 'browsed', to: 'users#browsed'  # 添加浏览记录(足迹)
      get 'unbrowse', to: 'users#unbrowse'  # 删除浏览记录(足迹)
      get 'favorites', to: 'users#favorites'  # 所有收藏
      get 'favorited' => 'users#favorited'  # 添加收藏
      get 'unfavorite' => 'users#unfavorite'  # 取消收藏
      get 'orders' => 'users#orders'  # 我的订单
      get 'shopcart', to: 'users#shopcart'  # 加入购物车
      get 'purchased', to: 'users#purchased'  # 我的订购
    end

    scope :goods do
      get 'info' => 'goods#info'  # 商品详情
      get 'favorited' => 'goods#favorited'  # 是否收藏
    end

    scope :adverts do
      get 'list' => 'goods#adverts'
    end
    scope :mall do
      get 'discoverList' => 'goods#discovers'
      
      scope :goodsOrder do
        get 'commitData' => 'users#orders'
        get 'getMyOrderList' => 'users#orders'
      end
    end
    scope :home do
      get 'hostGoodsList' => 'goods#recommends'
    end

    get '/' => 'base#debug'
  end
  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    skip_authorization
    result = {}
    @businesses = params[:q].present? ? Business.where('name LIKE ?', "%#{params[:q]}%") : Business.all
    if params[:page].present?
      surplus = @businesses.page(params[:page]).per(ENV['PER_PAGE'])
      result = {
        results: surplus.map { |b| { id: b.id, text: b.name } },
        pagination: {
          more: surplus.size > params[:page].to_i * per_page
        }
      }
    end
    respond_to do |format|
      format.html do
        @businesses
      end
      format.json do
        render json: result
      end
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:q, :p, :name, :brand_name
      )
    end
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>