config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :resources
  resources :discovers
  resources :orders
  resources :settings
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :member
  end
  resource :setting
  resources :skus do
    get 'base', on: :collection
  end
  resources :visitors
  resources :businesses
  resources :adverts
  resources :discovers
  resources :goods do
    get 'recommends', on: :collection
  end

  namespace :api, defaults: { format: :json } do
    post :adverts, to: 'base#adverts'
    post :discovers, to: 'base#discovers'
    post :recommends, to: 'base#recommends'
    post :detail, to: 'base#detail'
    get 'adverts' => 'goods#adverts'
    get 'discovers' => 'goods#discovers'
    # get 'login' => 'base#login'
    scope :sms do
      get 'send' => 'base#send_verify'
    end
    scope :wechat do
      get 'jscode2session', to: 'wechat#jscode2session'
    end

    scope :users do
      get 'register', to: 'users#register'  # 绑定手机
      get 'info', to: 'users#info'  # 用户信息(手机绑定)
      get 'browses', to: 'users#browses'  # 所有浏览记录(足迹)
      get 'browsed', to: 'users#browsed'  # 添加浏览记录(足迹)
      get 'unbrowse', to: 'users#unbrowse'  # 删除浏览记录(足迹)
      get 'favorites', to: 'users#favorites'  # 所有收藏
      get 'favorited' => 'users#favorited'  # 添加收藏
      get 'unfavorite' => 'users#unfavorite'  # 取消收藏
      get 'orders' => 'users#orders'  # 我的订单
      get 'shopcart', to: 'users#shopcart'  # 加入购物车
      get 'purchased', to: 'users#purchased'  # 我的订购
    end

    scope :goods do
      get 'info' => 'goods#info'  # 商品详情
      get 'favorited' => 'goods#favorited'  # 是否收藏
    end

    scope :adverts do
      get 'list' => 'goods#adverts'
    end
    scope :mall do
      get 'discoverList' => 'goods#discovers'
      
      scope :goodsOrder do
        get 'commitData' => 'users#orders'
        get 'getMyOrderList' => 'users#orders'
      end
    end
    scope :home do
      get 'hostGoodsList' => 'goods#recommends'
    end

    get '/' => 'base#debug'
  end
  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="newBaseSkuModalLabel"><%= @resource.new_record? ? '新增' : '编辑' %>类型</h4>
</div>
<%= simple_form_for(@resource, html: { class: 'form-horizontal' }) do |form| %>
<div class="modal-body">
  <% flash[:errors] = @resource.errors.full_messages if @resource.errors.any? %>

  <div class="form-group form-inputs">
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control', required: true, placeholder: '请输入类型名称' %>
    </div>
  </div>

</div>
<div class="modal-footer form-actions">
  <%= form.button :button, '关闭', type: 'button', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= form.button :submit, class: 'btn btn-primary' %>
</div>
<% end %>

app/views/resources/edit.html.erb
<%= render 'resources/form' %>

app/views/resources/index.html.erb
<section class="content-header">
  <h1>类型列表</h1>
  <div class="tools">
    <%= link_to "新增类型", new_resource_path, class: 'btn btn-sm btn-primary pull-right', data: { toggle: 'modal', target: '#newBaseSkuModal' } %>
  </div>
</section>

<section class="content container-fluid">
  <table class="table table-bordered table-condensed table-striped">
    <thead align="center">
      <tr>
        <th>ID</th>
        <th>名称</th>
        <th>类型 ID</th>
        <th>类型名称</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.id %></td>
        <td><%= resource.name %></td>
        <td><%= resource.resource_id %></td>
        <td><%= resource.resource_type %></td>
        <td>
          <%= link_to '详情', resource %>
          <%= link_to "编辑", edit_resource_path(resource) %>
          <%= link_to "删除", resource, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

<div class="modal fade" id="newBaseSkuModal" tabindex="-1" role="dialog" aria-labelledby="newBaseSkuModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<script>
$("#newBaseSkuModal").on("hidden.bs.modal", function(e){
  $(this).removeData("bs.modal");
});
</script>

app/views/resources/new.html.erb
<%= render 'resources/form' %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>