config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :resources
  resources :discovers
  resources :orders
  resources :settings
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :member
  end
  resource :setting
  resources :skus do
    get 'base', on: :collection
  end
  resources :visitors
  resources :businesses
  resources :adverts
  resources :discovers
  resources :goods do
    get 'recommends', on: :collection
  end

  namespace :api, defaults: { format: :json } do
    post :adverts, to: 'base#adverts'
    post :discovers, to: 'base#discovers'
    post :recommends, to: 'base#recommends'
    post :detail, to: 'base#detail'
    get 'adverts' => 'goods#adverts'
    get 'discovers' => 'goods#discovers'
    # get 'login' => 'base#login'
    scope :sms do
      get 'send' => 'base#send_verify'
    end
    scope :wechat do
      get 'jscode2session', to: 'wechat#jscode2session'
    end

    scope :users do
      get 'register', to: 'users#register'  # 绑定手机
      get 'info', to: 'users#info'  # 用户信息(手机绑定)
      get 'browses', to: 'users#browses'  # 所有浏览记录(足迹)
      get 'browsed', to: 'users#browsed'  # 添加浏览记录(足迹)
      get 'unbrowse', to: 'users#unbrowse'  # 删除浏览记录(足迹)
      get 'favorites', to: 'users#favorites'  # 所有收藏
      get 'favorited' => 'users#favorited'  # 添加收藏
      get 'unfavorite' => 'users#unfavorite'  # 取消收藏
      get 'orders' => 'users#orders'  # 我的订单
      get 'shopcart', to: 'users#shopcart'  # 加入购物车
      get 'purchased', to: 'users#purchased'  # 我的订购
    end

    scope :goods do
      get 'info' => 'goods#info'  # 商品详情
      get 'favorited' => 'goods#favorited'  # 是否收藏
    end

    scope :adverts do
      get 'list' => 'goods#adverts'
    end
    scope :mall do
      get 'discoverList' => 'goods#discovers'
      
      scope :goodsOrder do
        get 'commitData' => 'users#orders'
        get 'getMyOrderList' => 'users#orders'
      end
    end
    scope :home do
      get 'hostGoodsList' => 'goods#recommends'
    end

    get '/' => 'base#debug'
  end
  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/good.rb
# == Schema Information
#
# Table name: goods
#
#  id                       :bigint(8)        not null, primary key
#  uid(商品条码)                :string(255)      default("")
#  name(商品名称)               :string(255)
#  title(广告标题)              :string(255)
#  code(产品编码)               :string(255)      default("")
#  brand_name(品牌名称)         :string(255)      default("")
#  logo(图标)                 :string(255)      default("")
#  thum_logo(缩略图)           :string(255)      default("")
#  stock_num(库存)            :integer          default(0)
#  price((进货)价格)            :integer          default(0)
#  market_price(商城价)        :integer          default(0)
#  whole_price(分享价)         :integer          default(0)
#  whole_num((享受分享价条件)分享次数) :integer          default(0)
#  share_tips(分享提示)         :string(255)      default("0")
#  share_times(分享次数)        :integer          default(0)
#  share_amount(总分享次数)      :integer          default(0)
#  min_buy_num(最少购买数量)      :integer          default(0)
#  free_ship_num(免运费数量)     :integer          default(0)
#  freight(单件运费)            :integer          default(0)
#  sale_count(总销量)          :integer          default(0)
#  source_flag              :integer          default(0)
#  evaluate_count(评估值)      :integer          default(0)
#  start_time(活动开始时间)       :datetime
#  valid_end_time(活动截止时间)   :datetime
#  status(状态)               :integer          default(0)
#  detail_info(详细信息)        :text(65535)
#  discover(是否为好商品)         :boolean          default(FALSE)
#  recommend(是否为推荐商品)       :boolean          default(FALSE)
#  business_id(公司信息)        :bigint(8)
#  adverts_id(是否为广告商品)      :bigint(8)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_goods_on_adverts_id   (adverts_id)
#  index_goods_on_business_id  (business_id)
#  index_goods_on_code         (code) UNIQUE
#  index_goods_on_name         (name) UNIQUE
#  index_goods_on_uid          (uid) UNIQUE
#

class Good < ApplicationRecord
  has_many :photos
  has_many :good_visitors
  has_many :visitors, through: :good_visitors
  belongs_to :business
  belongs_to :advert, optional: true
  has_many :skus
  accepts_nested_attributes_for :skus, allow_destroy: true
  validates :name, presence: true, uniqueness: true

  scope :adverts, -> { where.not(adverts_id: nil) }
  scope :discovers, -> { where(discover: true) }
  scope :recommends, -> { where.not(title: nil) }
end

app/controllers/api/goods_controller.rb
class Api::GoodsController < Api::BaseController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :authenticate_user!

  def adverts
    skip_authorization
    adverts = Advert.where(deleted: false).limit(6)
    unless adverts.empty?
      @result = {
        code: 0,
        list: adverts,
        reason: ''
      }
    end
    render json: @result
  end

  def discovers
    skip_authorization
    discovers = Discover.all
    if sign_verified?
      @result = {
        code: 0,
        list: discovers,
        reason: ''
      }
    end
    render json: @result
  end

  # GET hostGoodsList.json
  def recommends
    skip_authorization
    if sign_verified?
      recommends = Good.all.page(params[:page]).per(params[:size])
      @result = {
        code: 0,
        list: recommends,
        page_total: recommends.total_pages
      }
    end
    render json: @result
  end

  def goods
    skip_authorization
    goods = Good.all
    render json: goods
  end

  def info
    skip_authorization
    if sign_verified?
      good = Good.find(params[:id])
      now = Time.zone.now
      valid = good.start_time < now && good.valid_end_time > now
      @result = {
        code: 0,
        data: good,
        photos: good.photos,
        skus: good.skus,
        validDate: valid ? 1 : 0
      }
    end
    render json: @result
  end

  # 是否收藏
  def favorited
    skip_authorization
    if sign_verified
      visitor = Visitor.find_by(uid: params[:openid])
      # favorited = visitor.goods.include?(Good.find(params[:id]))
      @result = {
        code: 0,
        favorited: GoodVisitor.favorited?(visitor.id, params[:id])
      }
    end
    render json: @result
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
    skip_authorization
  end

  # GET /goods
  # GET /goods.json
  def recommends
    skip_authorization
    @goods = Good.recommends
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
    skip_authorization
  end

  # GET /goods/new
  def new
    skip_authorization
    @good = Good.new
    @sku = @good.skus.new
  end

  # GET /goods/1/edit
  def edit
    skip_authorization
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to :goods, notice: "已创建编号为 '#{@good.code}' 的商品." }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    skip_authorization
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to edit_good_path(@good), notice: "编号为 '#{@good.code}' 的商品已更新." }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:id, :uid, :name, :title, :code, :brand_name, :logo, :thum_logo,
                                   :stock_num, :price, :market_price, :whole_price, :whole_num, :share_tips,
                                   :share_times, :share_amount, :min_buy_num, :free_ship_num, :freight,
                                   :sale_count, :source_flag, :evaluate_count, :start_time, :valid_end_time,
                                   :status, :detail_info, :discover, :recommend, :business_id, :adverts_id,
                                   skus_attributes: [:id, :name, :defaulted, :price, :sale_count, :category_id,
                                                     :stock_num, :stock_num_warn, :_destroy])
    end
end

app/views/goods/_form.html.erb
<%= simple_nested_form_for(@good, url: @good.new_record? ? goods_path : good_path(@good), html: { class: 'form-horizontal horizontal_form' }) do |form| %>
  <% flash[:errors] = @good.errors.full_messages if @good.errors.any? %>

  <%= form.input :uid, disabled: true %>
  <%= form.association :business, prompt: '请选择公司' %>
  <%= form.input :brand_name, disabled: true %>
  <%= form.input :name, required: true, placeholder: '请输入商品名称' %>
  <%= form.input :code, required: true, placeholder: '请输入商品编码' %>
  <%= form.input :title, placeholder: '请输入推荐标题' %>
  <%= form.input :logo, required: true, placeholder: '请输入商品图片' %>
  <%= form.input :thum_logo, required: true, placeholder: '请输入商品缩略图' %>
  <%= form.input :stock_num, as: :integer, required: true, placeholder: '请输入库存数量' %>
  <%= form.input :price, as: :decimal, required: true, placeholder: '请输入价格' %>
  <%= form.input :market_price, as: :decimal, required: true, placeholder: '请输入商城价' %>
  <%= form.input :whole_price, as: :decimal, placeholder: '请输入分享价' %>
  <%= form.input :whole_num, as: :integer, placeholder: '请输入分享次数(即享受分享价的条件)' %>
  <%= form.input :share_tips, placeholder: '请输入分享提示' %>
  <%= form.input :share_times, as: :integer, placeholder: '请输入已分享次数' %>
  <%= form.input :share_amount, as: :integer, placeholder: '请输入已分享次数合计' %>
  <%= form.input :min_buy_num, as: :integer, required: true, placeholder: '请输入最少购买数' %>
  <%= form.input :freight, as: :decimal, required: true, placeholder: '请输入运费金额' %>
  <%= form.input :free_ship_num, as: :integer, placeholder: '请输入免运费件数' %>
  <%= form.input :sale_count, as: :integer, placeholder: '请输入已售件数合计' %>
  <%= form.input :source_flag, as: :integer, placeholder: '请输入 Source Flag(可能是推荐\首页广告\好商品的标记)' %>
  <%= form.input :evaluate_count, as: :integer, placeholder: '请输入评估值 Evaluate Count' %>
  <%= form.input :status, as: :integer, placeholder: '请输入状态' %>


<!--
  <% if @good.skus.present? %>
  <div class="form-group">
    <%= form.label :skus, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <dl class="dl-horizontal">
        <% @good.skus.each do |gs| %>
        <dt><%= gs.name %></dt>
        <dd><%= gs.name %></dd>
        <% end %>
      </dl>
    </div>
  </div>
  <% end %>
-->
  <div class="form-group good-skus">
      <label class="col-sm-3 control-label">
        <%= form.link_to_add '添加库存属性', :skus, data: { target: '#goodSkus' }, class: 'btn btn-xs btn-info pull-right skus-btn' %>
      </label>
      <div class="col-sm-9">
        <table id="goodSkus">
          <tr>
            <th>属性</th>
            <th>价格</th>
            <th>库存</th>
            <th>警戒</th>
            <th>操作</th>
          </tr>
        <%= form.fields_for :skus, wrapper: false do |good_sku| %>
          <tr class='fields'>
            <td><%= good_sku.select :category_id, Category.normal.map { |c| [c.name, c.id]}, {} %></tda>
            <td><%= good_sku.number_field :price %></td>
            <td><%= good_sku.number_field :stock_num, min: 0 %></td>
            <td><%= good_sku.number_field :stock_num_warn, min: 0 %></td>
            <td><%= good_sku.link_to_remove '删除', class: 'btn btn-xs btn-info' %></td>
          </tr>
        <% end %>
        </table>
      </div>
  </div>

  <%= form.input :detail_info, as: :text, input_html: { rows: 40 } %>

  <div class="actions">
    <%= form.submit class: 'btn btn-block btn-info' %>
  </div>
<% end %>

<script>
$('#good_detail_info').wysihtml5({locale: 'zh-CN'});

// 商品属性级联操作
function associationSku(e){
  let target = e.target;
  let baseSkuId = target.value;
  let normal = $(target).parents('.fields').find('.good-sku-normal').first();
  $.ajax({
    url: '/skus',
    type: 'GET',
    dataType: 'json',
    data: {
      base_id: baseSkuId
    },
    success: function(data, status, xhr) {
      let options = '';
      if (data.length === 0) {
        options = "<option value=''>无</option>";
      } else {
        data.forEach(function(item, index) {
          options += "<option value='" + item.id + "'>" + item.name + "</option>";
        });
      }
      normal.html(options);
    }
  })
}

$(function(){
  $('.select2').select2({
    ajax: {
      url: '/businesses',
      method: 'GET',
      delay: 1000,  // wait 250 milliseconds before triggering the request
      dataType: 'json',
      data: function (params) {
        console.log('params = ', params);
        // Query parameters will be ?search=[term]&page=[page]
        return {
          q: params.term,
          page: params.page || 1
        };
      },
      processResults: function (data, params) {
        console.log('Ajax result = ', data);
        params.page = params.page || 1;
        return data;
        /**
        return {
          results: data.results,
          pagination: {
            more: (params.page * 30) < data.total
          }
        };
        **/
      },
      cache: true,
      placeholder: '',
      minimumInputLength: 1
    }
  });
});
</script>

app/views/goods/edit.html.erb
<section class="content-header">
  <h1>编辑推荐商品</h1>
  <div class="tools">
    <%= link_to "返回列表", recommends_goods_path, class: 'btn btn-sm btn-default pull-right' %>
  </div>
</section>

<section class="content container-fluid">
  <%= render 'goods/form' %>
</section>

app/views/goods/index.html.erb
<section class="content-header">
  <h1>商品列表</h1>
  <div class="tools">
    <%= link_to "新建商品", new_good_path, class: 'btn btn-sm btn-primary pull-right' %>
  </div>
</section>

<section class="content container-fluid">
  <table class="table table-bordered table-condensed table-striped">
    <thead align="center">
      <tr>
        <th>ID</th>
        <th>商品名称</th>
        <th>编码</th>
        <th>品牌</th>
        <th>公司名称</th>
        <th>广告</th>
        <th>推荐</th>
        <th>好商品</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @goods.each do |good| %>
      <tr>
        <td><%= good.id %></td>
        <td><%= good.name %></td>
        <td><%= good.code %></td>
        <td><%= good.brand_name %></td>
        <td><%= good.business.name %></td>
        <td><%= good.advert.present? ? '是' : '否' %></td>
        <td><%= good.recommend ? '是' : '否' %></td>
        <td><%= good.discover ? '是' : '否' %></td>
        <td>
          <%= link_to '详情', good %>
          <%= link_to "编辑", edit_good_path(good) %>
          <%= link_to "删除", good, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/goods/new.html.erb
<section class="content-header">
  <h1>新建推荐商品</h1>
  <div class="tools">
    <%= link_to "返回列表", recommends_goods_path, class: 'btn btn-sm btn-default pull-right' %>
  </div>
</section>

<section class="content container-fluid">
  <%= render 'goods/form' %>
</section>

app/views/goods/recommends.html.erb
<section class="content-header">
  <h1>商品推荐列表</h1>
  <div class="tools">
    <%= link_to "新建推荐", new_good_path, class: 'btn btn-sm btn-primary pull-right' %>
  </div>
</section>

<section class="content container-fluid">
  <table class="table table-bordered table-condensed table-striped">
    <thead align="center">
      <tr>
        <th>ID</th>
        <th>商品名称</th>
        <th>编码</th>
        <th>品牌</th>
        <th>公司名称</th>
        <th>广告</th>
        <th>推荐</th>
        <th>好商品</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @goods.each do |good| %>
      <tr>
        <td><%= good.id %></td>
        <td><%= good.name %></td>
        <td><%= good.code %></td>
        <td><%= good.brand_name %></td>
        <td><%= good.business.name %></td>
        <td><%= good.advert.present? ? '是' : '否' %></td>
        <td><%= good.recommend ? '是' : '否' %></td>
        <td><%= good.discover ? '是' : '否' %></td>
        <td>
          <%= link_to '详情', good %>
          <%= link_to "编辑", edit_good_path(good) %>
          <%= link_to "删除", good, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>