config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :resources
  resources :discovers
  resources :orders
  resources :settings
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :member
  end
  resource :setting
  resources :skus do
    get 'base', on: :collection
  end
  resources :visitors
  resources :businesses
  resources :adverts
  resources :discovers
  resources :goods do
    get 'recommends', on: :collection
  end

  namespace :api, defaults: { format: :json } do
    post :adverts, to: 'base#adverts'
    post :discovers, to: 'base#discovers'
    post :recommends, to: 'base#recommends'
    post :detail, to: 'base#detail'
    get 'adverts' => 'goods#adverts'
    get 'discovers' => 'goods#discovers'
    # get 'login' => 'base#login'
    scope :sms do
      get 'send' => 'base#send_verify'
    end
    scope :wechat do
      get 'jscode2session', to: 'wechat#jscode2session'
    end

    scope :users do
      get 'register', to: 'users#register'  # 绑定手机
      get 'info', to: 'users#info'  # 用户信息(手机绑定)
      get 'browses', to: 'users#browses'  # 所有浏览记录(足迹)
      get 'browsed', to: 'users#browsed'  # 添加浏览记录(足迹)
      get 'unbrowse', to: 'users#unbrowse'  # 删除浏览记录(足迹)
      get 'favorites', to: 'users#favorites'  # 所有收藏
      get 'favorited' => 'users#favorited'  # 添加收藏
      get 'unfavorite' => 'users#unfavorite'  # 取消收藏
      get 'orders' => 'users#orders'  # 我的订单
      get 'shopcart', to: 'users#shopcart'  # 加入购物车
      get 'purchased', to: 'users#purchased'  # 我的订购
    end

    scope :goods do
      get 'info' => 'goods#info'  # 商品详情
      get 'favorited' => 'goods#favorited'  # 是否收藏
    end

    scope :adverts do
      get 'list' => 'goods#adverts'
    end
    scope :mall do
      get 'discoverList' => 'goods#discovers'
      
      scope :goodsOrder do
        get 'commitData' => 'users#orders'
        get 'getMyOrderList' => 'users#orders'
      end
    end
    scope :home do
      get 'hostGoodsList' => 'goods#recommends'
    end

    get '/' => 'base#debug'
  end
  root 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_aside.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <ul class="sidebar-menu" data-widget="tree">
      <li class="treeview <%#= 'active' if controller_name == 'courses' %>">
        <a href="#">
          <i class="fa fa-book"></i>
          <span>商品管理</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="<%= goods_path %>">商品列表</a>
          </li>
          <li>
            <a href="<%= adverts_path %>">首页广告</a>
          </li>
          <li>
            <a href="<%= discovers_path %>">发现好商品</a>
          </li>
          <li>
            <a href="<%= recommends_goods_path %>">商品推荐</a>
          </li>
        </ul>
      </li>

      <li class="treeview <%#= 'active' if controller_name == 'courses' %>">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>用户管理</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="<%= users_path %>">管理员</a>
          </li>
          <li>
            <a href="<%= visitors_path %>">普通用户</a>
          </li>
        </ul>
      </li>

      <li class="<%= 'active' if controller_name == 'users' && action_name == 'profile' %>">
        <a href="<%= profile_user_path(current_user) %>">
          <i class="fa fa-gear"></i>
          <span>个人设置</span>
        </a>
      </li>

      <li class="treeview <%#= 'active' if controller_name == 'courses' %>">
        <a href="#">
          <i class="fa fa-cogs"></i>
          <span>其他管理</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="<%= categories_path %>">类型管理</a>
          </li>
          <li>
            <a href="<%= skus_path %>">库存单位</a>
          </li>
          <li>
            <a href="<%= visitors_path %>">普通用户</a>
          </li>
        </ul>
      </li>
      
    </ul>
  </section>
</aside>

app/views/layouts/_content.html.erb
<div class="content-wrapper">
  <%= yield %>
</div>

app/views/layouts/_control.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active">
      <a href="#control-sidebar-home-tab" data-toggle="tab">
        <i class="fa fa-home"></i>
      </a>
    </li>
    <li>
      <a href="#control-sidebar-settings-tab" data-toggle="tab">
        <i class="fa fa-gears"></i>
      </a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="pull-right-container">
                <span class="label label-danger pull-right">70%</span>
              </span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<div class="control-sidebar-bg"></div>

app/views/layouts/_footer.html.erb
<!-- To the right -->
<div class="pull-right hidden-xs">
  鄂 ICP 备 16005840 号 - 1	
</div>
<!-- Default to the left -->
<strong>Copyright &copy; 2016
  <a href="<%= root_path %>">JJERP.CN</a>.
</strong> All rights reserved.

app/views/layouts/_header.html.erb
<header class="main-header">

  <a href="#" class="logo">
    <span class="logo-mini"><b><%= t(:short_app_name) %></b></span>
    <span class="logo-lg"><%= t :app_name %></span>
  </a>

  <nav class="navbar navbar-static-top" role="navigation">
    
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <li class="dropdown course-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="我的课程">
            <i class="fa fa-book"></i>
            <span class="navbar-title">我的课程</span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">已购课程</a>
            </li>
            <li>
              <a href="#">自主选课</a>
            </li>
            <li>
              <a href="#">已发布</a>
            </li>
            <li>
              <a href="#">草稿箱</a>
            </li>
          </ul>
        </li>

        <li class="dropdown attention-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="我的关注">
            <i class="fa fa-heart"></i>
            <span class="navbar-title">我的关注</span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">关注的班级</a>
            </li>
            <li>
              <a href="#">关注的课程</a>
            </li>
            <li>
              <a href="#">关注的人</a>
            </li>
            <li>
              <a href="#">关注的素材</a>
            </li>
          </ul>
        </li>

        <li class="dropdown partner-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="支持合作">
            <i class="fa fa-question-circle"></i>
            <span class="navbar-title">支持合作</span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">开班指南</a>
            </li>
            <li>
              <a href="#">工具介绍</a>
            </li>
            <li>
              <a href="#">客服运营</a>
            </li>
            <li>
              <a href="#">互助论坛</a>
            </li>
            <li>
              <a href="#">机构合作</a>
            </li>
          </ul>
        </li>

        <% if user_signed_in? %>

        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="通知">
            <i class="fa fa-bell"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">收到 <%= 4 %> 条信息</li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <%= image_tag 'user2-160x160.jpg', alt: 'User Image', class: 'img-circle' %>
                    </div>
                    <h4>
                      Support Team
                      <small>
                        <i class="fa fa-clock"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#">查看所有信息</a>
            </li>
          </ul>
        </li>

        <li class="dropdown user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="个人信息">
            <%= image_tag current_user.avatar.url(:thumb), alt: 'User Image', class: 'user-image' %>
            <!-- <span class="hidden-xs"><%= current_user.email %></span> -->
          </a>
          <ul class="dropdown-menu">
            <li>
              <strong class='nav-header-current-user'><%= current_user.email %></strong>
            </li>
            <li class="dropdown-divider"></li>
            <li>
              <a href="#" class="btn btn-default btn-flat">我的任务</a>
            </li>
            <li>
              <a href="#" class="btn btn-default btn-flat">收藏夹</a>
            </li>
            <li>
              <a href="#" class="btn btn-default btn-flat">我要推广</a>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
              <a href="#" data-toggle="control-sidebar">系统设置</a>
            </li>
            <li>
              <%= link_to '个人设置', '#', class: 'btn btn-default btn-flat' %>
            </li>
            <li class="dropdown-divider"></li>
            <li>
              <%= link_to '退出', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
            </li>
          </ul>
        </li>

        <% else %>

        <li class="user login">
          <a href="<%= new_user_session_path %>" title="登录">
            <i class="fa fa-user"></i>
            <span class="navbar-title">登录</span>
          </a>
        </li>

        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_message.html.erb
<% if flash.present? && flash.keys.present? %>
  <% messages = flash.delete(:timedout) %>
  <% messages.keys.each do |key, value| %>
    <% if singular?(key) %> <!--// 信息 key 为单数时，直接输出 -->
    <script type="text/javascript">
      noty({
        type: "<%= bootstrap_noty(key) %>", // 可选值：success, error, warning, information, notification
        text: "<%= messages[key] %>", // [string|html] need display content
      });
    </script>
    <% else %> <!--// 信息 key 为复数时，遍历后输出 -->
      <% messages[key].each do |v| %>
      <script type="text/javascript">
        noty({
          type: "<%= bootstrap_noty(key.singularize) %>",
          text: "<%= v %>",
        });
      </script>
      <% end %>
    <% end %>
  <% end %>
  <% flash.discard %><!-- 清空 flash 信息，防止页面刷新时重复弹出 -->
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="https://cdn.bootcss.com/html5shiv/r29/html5.min.js"></script>
  <script src="https://cdn.bootcss.com/html5shiv/r29/respond.min.js"></script>
  <script src="https://cdn.bootcss.com/html5shiv/r29/excanvas.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV['APP_NAME'] %></title>
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/png' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="hold-transition skin-blue-light sidebar-mini sidebar-collapse">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/aside' %>
      <%= render 'layouts/content' %>
      <footer class="main-footer">
        <%= render 'layouts/footer' %>
      </footer>
      <%= render 'layouts/control' %>
      <%= render 'layouts/message' %>
    </div>
  </body>
</html>

app/views/layouts/whole.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV['APP_NAME'] %></title>
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/png' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="hold-transition skin-blue-light sidebar-mini">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div class="content-wrapper fullayout">
        <section class="content container-fluid">
          <%= yield %>
        </section>
      </div>
      <footer class="main-footer fullayout">
        <%= render 'layouts/footer' %>
      </footer>
      <%= render 'layouts/message' %>
    </div>
  </body>
</html>